feat: add mobile version
qsok3d/fake-burrberry-frontend pull request #1
Opened 2017-08-01 09:03 UTC by qsok3d

2017-08-01 12:17 UTC, evgenyrodionov commented
Проверю в 8

2017-08-01 18:22 UTC, evgenyrodionov commented
https://rawgit.com/qsok3d/fake-burrberry-frontend/feat/product-page/index.html

![image](https://user-images.githubusercontent.com/775692/28840311-44f53e78-76ff-11e7-900b-7ed8e36666c5.png)
![image](https://user-images.githubusercontent.com/775692/28840326-52c618c4-76ff-11e7-863b-0531ef1472e8.png)
![image](https://user-images.githubusercontent.com/775692/28840345-5d4a4798-76ff-11e7-82f6-04d6f6a3510e.png)
![image](https://user-images.githubusercontent.com/775692/28840354-634b150a-76ff-11e7-9573-049ffe4e6beb.png)
![image](https://user-images.githubusercontent.com/775692/28840380-763afbf8-76ff-11e7-8641-5b7c474a9e80.png)

2017-08-01 18:22 UTC, imevro submitted a review, later dismissed
фикси дизайн + нейминг не по кодстайлу

2017-08-02 10:51 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28870589-7bc6ea70-7789-11e7-9dcf-4bb295f25d63.png)
![image](https://user-images.githubusercontent.com/775692/28870594-82fe19a8-7789-11e7-88f8-c07030f580ce.png)
![image](https://user-images.githubusercontent.com/775692/28870603-8b13fd74-7789-11e7-9458-27e9e5dcd148.png)
![image](https://user-images.githubusercontent.com/775692/28870611-9133f61e-7789-11e7-8c54-e66d30564374.png)

2017-08-03 11:40 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28920257-ab24ec4c-7859-11e7-87e8-6cf5de3c47ab.png)
![image](https://user-images.githubusercontent.com/775692/28920269-b3d04b7a-7859-11e7-9c47-33c6819425bd.png)

2017-08-03 15:04 UTC, qsok3d commented
В блоке More For You поправил все, но не понятно у меня не получается пиксель в пиксель сделать, я даже не знаю что уже придумать. Возможно не правильно накладываю конечно.
Делал все что можно марджины паддинги line-height и даже переверстал уже этот блок

2017-08-03 20:38 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28942571-84f63ca6-78a4-11e7-8575-527969c0202f.png)
![image](https://user-images.githubusercontent.com/775692/28942582-8c6d959c-78a4-11e7-80ed-ebb9cee5ff2c.png)
![image](https://user-images.githubusercontent.com/775692/28942593-99be53f8-78a4-11e7-9ed8-ae52d36fa382.png)
![image](https://user-images.githubusercontent.com/775692/28942604-a5f1c272-78a4-11e7-8a7c-2fa66d2bd33b.png)

2017-08-03 20:41 UTC, imevro requested changes
БЭМ

2017-08-03 20:41 UTC, evgenyrodionov commented on style.css
> +  content: url(img/triangle_reverse.svg);
используй transform rotate, зачем два файла

2017-08-04 09:50 UTC, evgenyrodionov commented
Проверка судя по всему была на 12 утра, поэтому проверю в 3

2017-08-04 12:51 UTC, imevro requested changes

2017-08-04 12:51 UTC, evgenyrodionov commented on style.css
> +.more-menu__item{
итем плохой нейминг

2017-08-04 18:13 UTC, imevro approved these changes

2017-08-05 15:28 UTC, evgenyrodionov commented
Ты сетку используешь? почему на десктопной версии деливери не справа? плюс картинка уползла влево
нижние товары распидорасило

![image](https://user-images.githubusercontent.com/775692/28996559-c7fb6856-7a0b-11e7-86e4-1b8081cf2710.png)
![image](https://user-images.githubusercontent.com/775692/28996562-d6f01118-7a0b-11e7-9165-9691b7fade29.png)

2017-08-05 15:32 UTC, imevro requested changes
↑

2017-08-05 18:35 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28997790-ec634e6a-7a25-11e7-8ec4-5fa7738e208e.png)
![image](https://user-images.githubusercontent.com/775692/28997792-f35945c6-7a25-11e7-8574-bba2c5c703b7.png)
![image](https://user-images.githubusercontent.com/775692/28997793-fbce04bc-7a25-11e7-81b6-84bc1fe88a1a.png)

2017-08-05 18:38 UTC, imevro requested changes
↑

2017-08-05 18:38 UTC, evgenyrodionov commented
По коду норм

2017-08-06 07:52 UTC, imevro approved these changes

2017-08-06 07:52 UTC, merged

2017-08-06 07:53 UTC, evgenyrodionov commented
Переключаешься на мастер, делаешь гит пулл --ребейз ориджин мастер, все новые бранчи от этого мастера